# -*- coding: utf-8 -*-
"""Horario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhrbsVhtIm9C9YBunuI2W_v-rx9epTEN
"""

print("1.voleibol")
print("2.Taller de Física Mecánica")
print("3.Algebra Lineal")
print("4.Física Mecánica")
print("5.Calculo Diferencial")
print("6.Programación a Sistemas Mecatrónicos")
print("7.Dibujo de Ingeniería")
print("8.Fundamentos de Investigación")
Mat = ["voleibol","Taller de Física Mecánica","Algebra Lineal","Física Mecánica","Calculo Diferencial","Programación a Sistemas Mecatrónicos","Dibujo de Ingeniería","Fundamentos de Investigación"]
Day = ["Lunes","martes","miercoles","jueves","viernes"]
hour = [7,9,11,1,3]
salon = ["Polideportivo",304,303,405, 303,303,305]
teacher = ["indefinido","Lalinde Jairo","Bohorquez Roberto","Pineda Hernan","Bohorquez Roberto","Torres David","Sanchez Juan","Cortes Julian"]


opc = input('Ingrese un numero: ')
if opc == "1":
    m = Mat[0]
    d = Day[0]
    h = [hour[1] ,hour[2]]
    s = salon[0]
    p = teacher[0]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}AM\nSalon es: {s}\nEl Profesor es: {p}")

elif opc == "2":
    m = Mat[1]
    d = Day[0]
    h = [hour[3] ,hour[4]]
    s = salon[1]
    p = teacher[1]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}PM\nSalon: {s}DB\nEl Profesor es: {p}")  
elif opc == "3":
    m = Mat[2]
    d = Day[1] , Day[3]
    h = [hour[0] ,hour[1]]
    s = salon[2]
    p = teacher[2]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}AM\nSalon: {s}DB\nEl Profesor es: {p}") 
elif opc == "4":
    m = Mat[3]
    d = Day[1] , Day[3]
    h = [hour[1] ,hour[2]]
    s = salon[3]
    p = teacher[3]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}AM\nSalon: {s}DB\nEl Profesor es: {p}") 
elif opc == "5":
    m = Mat[4]
    d = Day[1] , Day[3]
    h = [hour[2] ,hour[3]]
    s = salon[4]
    p = teacher[4]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}AM-PM\nSalon: {s}DB\nEl Profesor es: {p}")
elif opc == "6":
    m = Mat[5]
    d = Day[1] , Day[3]
    h = [hour[3] ,hour[4]]
    s = salon[4]
    p = teacher[5]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}PM\nSalon: {s}GO\nEl Profesor es: {p}")


if opc == "7":
    m = Mat[6]
    d = Day[4]
    h = [hour[1] ,hour[2]]
    s = salon[5]
    p = teacher[6]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}AM\nSalon es: {s} GO\nEl Profesor es: {p}")


if opc == "8":
    m = Mat[7]
    d = Day[4]
    h = [hour[2] ,hour[3]]
    s = salon[6]
    p = teacher[7]
    print(f"Asignatura: {m}\nDia: {d}\nHora: {h}AM-PM\nSalon es: {s} DB\nEl Profesor es: {p}")