# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dot95m1V3aWdgNr1wYL42Pn_iNczGDKC
"""

import random as r
def Crear_lista():
  lista = []
  for i in range(10):
     num = r.randint(1,50)
     lista.append(num)
  return lista
    
  
def numero_mayor(lista):
  
  mayor = lista[0]
  
  for i in range(0,len(lista)-1,1):
    Q = lista[i+1]
    
    if mayor < Q:
      mayor = Q
  return mayor



def es_primo(lista):
    for i in range(0,len(lista)-1):
      
      for n in range(2, i):
        if i % n == 0:
             print("No es primo", i, "es divisor")
             return False
      print("Es primo")
      return True


  


def main():
  lista = Crear_lista()
  mayor = numero_mayor(lista)
  numero_primo = es_primo(lista)
  print(lista)
  print(mayor)
  print(numero_primo )


if __name__ == "__main__":
  main()



