# -*- coding: utf-8 -*-
"""Diagrama_de_clases

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDl3SDlkPs3PKt7Y1UGybrH550HkKsPo
"""

class Ciudadano:
    def __init__(self, nombre: str, edad: int, cc: str):
        self.__nombre = nombre
        self.__edad = edad
        self.__cc = cc

    # Getters
    def getNombre(self) -> str:
        return self.__nombre

    def getEdad(self) -> int:
        return self.__edad

    def getCc(self) -> str:
        return self.__cc

    # Setters
    def setNombre(self, nombre: str):
        self.__nombre = nombre

    def setEdad(self, edad: int):
        if edad > 0:
            self.__edad = edad
        else:
            print("Edad inválida")

    def setCc(self, cc: str):
        if len(cc) >= 8 and len(cc) <= 10:
            self.__cc = cc
        else:
            print("Número de cédula inválido")

    def mostrar(self):
        print(f'Nombre: {self.__nombre} - Edad: {self.__edad} - CC: {self.__cc}')

    def esMayorDeEdad(self):
        if self.__edad >= 18:
            print("Es mayor de edad")
        else:
            print("No es mayor de edad")
def main():
  juan = Ciudadano("David",15,"1001428874")
  juan.mostrar()
  juan.esMayorDeEdad()
if __name__ == "__main__":
  main()
